name: Test
on: push
jobs:
    test: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: run tests in lab 1
              run: go test lab7/lab1/tests
            - name: run tests in lab 2
              run: go test lab7/lab2/functions/tests
