name: Test
on: fork
jobs:
    test: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: run tests
              run: go test TesingLab/lab1 ./tests
