name: Test
on: push
jobs:
    test: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: go to tests
              run: cd lab1/tests
            - name: run tests
              run: go test


